baseURL = "http://example.org/"
languageCode = "en-us"
title = "Cloud Architects"
theme = "hugo-theme-learn"

[deployment]
order = [".jpg$", ".gif$"]

[[deployment.targets]]
name = "deployment-to-production"
URL = "s3://www.cloudarchitects.solutions"


[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/Cloud-Architects/"
weight = 20
